# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atrack < Formula
  desc "Terminal CLI tool for tracking AI agent interactions"
  homepage "https://github.com/alfaXphoori/AgentTrack"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.0/AgentTrack_Darwin_x86_64.tar.gz"
      sha256 "2297705fe1723008cbfa26d4a3567519b78ed16dc573f5ec8f8a82878d0cd5b8"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.0/AgentTrack_Darwin_arm64.tar.gz"
      sha256 "9d5863056aee77746225861137a7d35ba2231306a29a2cde930f5b3fd1674db8"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.0/AgentTrack_Linux_x86_64.tar.gz"
      sha256 "0d8c5d553dc7cd5e4e34fa2d72a48708beccb589979b612c400be8ec13a18849"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.0/AgentTrack_Linux_arm64.tar.gz"
      sha256 "e7ec06150b7e2d3ad8592a1f2ed3f3ae8e9a408a021931ab913b4c4a7074f741"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  test do
    system "#{bin}/atrack", "--version"
  end
end
