# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atrack < Formula
  desc "Terminal CLI tool for tracking AI agent interactions"
  homepage "https://github.com/alfaXphoori/AgentTrack"
  version "0.14.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.1/AgentTrack_Darwin_x86_64.tar.gz"
      sha256 "708188305cf550b247e21fa5e35b641c8d07483c74e3508c1a5f742eaab72cdf"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.1/AgentTrack_Darwin_arm64.tar.gz"
      sha256 "abded98346643ccefc8c6401027ae513fa5380935bb7b932ca3d80de92cab9bc"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.1/AgentTrack_Linux_x86_64.tar.gz"
      sha256 "71bdd6acde466d79360a0b3109467d258d232d0472136067fcbe15771f85b8b1"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.14.1/AgentTrack_Linux_arm64.tar.gz"
      sha256 "ae8fe06ef6f51aabc0818aac9d986f41efe84d3f904c0bc9583b59afec50af66"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  test do
    system "#{bin}/atrack", "--version"
  end
end
