# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atrack < Formula
  desc "Terminal CLI tool for tracking AI agent interactions"
  homepage "https://github.com/alfaXphoori/AgentTrack"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.16.0/AgentTrack_Darwin_x86_64.tar.gz"
      sha256 "864e3771e7e7366f7a4a0be5d8f85adf24d00ef10bc1709cf71e2bba5ad16073"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.16.0/AgentTrack_Darwin_arm64.tar.gz"
      sha256 "1b2fca9cffac138b050e8668e2631bccf59ab1a1529f439cbfd1a7c89c9474d4"

      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.16.0/AgentTrack_Linux_x86_64.tar.gz"
      sha256 "2c5285ddb4ead15497ac5b53834f22ffb945fe254bf6bba4b59fd5d13ff32386"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alfaXphoori/AgentTrack/releases/download/v0.16.0/AgentTrack_Linux_arm64.tar.gz"
      sha256 "25d3a05d5c36f79fdad7857a2166ca37f5a77b738ce3454de65df74eac6adb17"
      define_method(:install) do
        bin.install "atrack"
        bin.install "scripts/gemiatrack.sh" => "gemiatrack"
        bin.install "scripts/gemini-cli-atrack.sh" => "gemini-cli-atrack"
        system bin/"atrack", "autostart", "install"
      end
    end
  end

  test do
    system "#{bin}/atrack", "--version"
  end
end
